# Generated by Django 3.1.3 on 2021-01-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('nr_dokumentu', models.CharField(max_length=50)),
                ('rodzaj_dok', models.CharField(default='Dowód osobisty', max_length=50)),
                ('miesiac_dok', models.CharField(default='1', max_length=50)),
                ('rok_dok', models.CharField(default='2021', max_length=50)),
                ('e_mail', models.EmailField(blank=True, max_length=50, null=True)),
                ('nr_telefonu', models.CharField(max_length=17)),
            ],
        ),
    ]
