# Generated by Django 3.1.3 on 2020-12-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilKlienta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='e_mail',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
