# Generated by Django 3.1.3 on 2021-03-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilKlienta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='miesiac_dok',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='klient',
            name='rok_dok',
            field=models.CharField(default='', max_length=50),
        ),
    ]
