# Generated by Django 3.1.3 on 2020-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilKlienta', '0002_auto_20201201_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
