# Generated by Django 3.1.3 on 2020-12-12 10:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('profilKlienta', '0004_klient_nr_telefonu'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='klient',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
