# Generated by Django 3.1.3 on 2020-12-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilKlienta', '0005_auto_20201212_1127'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='klient',
            managers=[
            ],
        ),
    ]
