# Generated by Django 3.1.3 on 2021-01-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprzet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asortyment',
            name='dostepnosc',
            field=models.CharField(default='Dostepny', max_length=20),
        ),
    ]
