# Generated by Django 3.1.3 on 2021-04-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprzet', '0002_asortyment_dostepnosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='asortyment',
            name='informacje_awaria',
            field=models.CharField(default='Brak informacji', max_length=200),
        ),
    ]
