# Generated by Django 3.1.3 on 2021-04-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notatka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=200)),
                ('status', models.CharField(default='Do zrobienia', max_length=25)),
                ('data_wykonania', models.DateField()),
            ],
        ),
    ]
