# Generated by Django 3.1.3 on 2021-01-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profilKlienta', '0001_initial'),
        ('sprzet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozpoczecia', models.DateField()),
                ('data_zakonczenia', models.DateField()),
                ('godzina_rozpoczecia', models.TimeField()),
                ('godzina_zakonczenia', models.TimeField()),
                ('status', models.CharField(default='brak', max_length=20)),
                ('id_klient', models.CharField(default=1, max_length=20)),
                ('id_sprzet', models.CharField(default=1, max_length=20)),
                ('platnosc', models.CharField(default=0, max_length=6)),
                ('rodzaj_platnosci', models.CharField(default='brak', max_length=30)),
                ('status_platnosci', models.CharField(default='Do zaplaty', max_length=30)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilKlienta.klient')),
                ('sprzet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprzet.asortyment')),
            ],
        ),
    ]
