# Generated by Django 3.1.3 on 2021-01-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profilKlienta', '0006_auto_20201212_1129'),
        ('sprzet', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozpoczecia', models.DateField()),
                ('data_zakonczenia', models.DateField()),
                ('godzina_rozpoczecia', models.TimeField()),
                ('godzina_zakonczenia', models.TimeField()),
                ('status', models.CharField(default='brak', max_length=20)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilKlienta.klient')),
                ('sprzet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprzet.asortyment')),
            ],
        ),
    ]
