# Generated by Django 3.1.3 on 2021-01-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczenie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wypozyczenie',
            name='data_platnosci',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
